### ISSUE TITLE
RDPC Pod Security: Update Dockerfile security workflow-ui

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/workflow-ui#28]
Refer to platform-ui Dockerfile:
https://github.com/icgc-argo/platform-ui/blob/develop/Dockerfile

The main process must run as user $APP_UID, not as root

**Comment by rosibaj** [comment]
as this is running in prod, we will secure this for now 
workflow ui in future  needs to be connected to wes-argo api

**Comment by rosibaj** [comment]
deploy to prod still needed
