### ISSUE TITLE
Update Cancel Button to use GraphQL Mutation 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-ui#69]
- [x] Update the `New Run` button to use the rdpc-gateway-api (https://api.rdpc-qa.cancercollaboratory.org) cancel mutation

![image](https://user-images.githubusercontent.com/15824252/96465813-62603a80-11f7-11eb-9264-6a59df14eeb2.png)

## Expected Outcome
When I cancel a run, i can check the console and see that the run button initiates a mutation through the graphql api

**Comment by rosibaj** [comment]
@mistryrn can you connect PR pls?

**Comment by mistryrn** [comment]
This is the PR for this ticket: https://github.com/icgc-argo/workflow-ui/pull/91

But the PR to merge it into the develop branch is this one: https://github.com/icgc-argo/workflow-ui/pull/92
