### ISSUE TITLE
Deploy ui-auth changes to QA 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-ui#78]
- rdpc infra and charts to addd qa env variables
- merging of charts?

**Comment by mistryrn** [comment]
### Workflow UI Ego Login Prod Release Guide

1. Create an Application for `workflow-ui` with the following values
    * Name: `workflow-ui`
    * Status: `APPROVED`
    * Application Type: `CLIENT`
    * Client ID: `workflow-ui`
    * Client Secret: `secret`
    * Redirect URI: `https://wes.rdpc.cancercollaboratory.org/logged-in`
2. Create a Policy for `RDPC-collab` with the following values:
    * Name: `RDPC-collab`
3. Create a Group for `workflow-ui-admin` with the following values:
    * Name: `workflow-ui-admin`
    * Status: `APPROVED`
    * Permissions: `RDPC-collab: WRITE`
4. Create a Group for `workflow-ui-member` with the following values:
    * Name: `workflow-ui-member`
    * Status: `APPROVED`
    * Permissions: `RDPC-collab: READ`
5. Add necessary members to each group based on required read/write permissions

**Comment by rosibaj** [comment]
- PR was approved on Friday and merged; changes are present in ui.
- still not seeing login here: https://wes.rdpc-qa.cancercollaboratory.org/

**Comment by rosibaj** [comment]
@mistryrn when you are back can you prepare a UI release to QA as well?

**Comment by mistryrn** [comment]
Steps 2-5 of the "Workflow UI Ego Login Prod Release Guide" in the comments above no longer apply.

`RDPC-collab` was used in error, the region should be `CA` instead. Policies and groups are already set up for `RDPC-CA` READ and WRITE permissions.

Therefore, to deploy to prod, only the following step must be done:

### Workflow UI Ego Login Prod Release Guide (Revised)
1. Create an Application for `workflow-ui` with the following values
* Name: `workflow-ui`
* Status: `APPROVED`
* Application Type: `CLIENT`
* Client ID: `workflow-ui`
* Client Secret: `secret`
* Redirect URI: `https://wes.rdpc.cancercollaboratory.org/logged-in`

The rest of the steps are no longer needed.
