### ISSUE TITLE
Environment Variables Lost After Jenkins Deploy

### ISSUE THREAD

**Issue by mistryrn** [icgc-argo/workflow-ui#80]
Environment variables seem to be disappearing after each Jenkins deploy following a PR merge to develop in the workflow-ui repo

For at least the following two merges, the Jenkins deploys have resulted in environment variables being lost:
- https://github.com/icgc-argo/workflow-ui/pull/73
- https://github.com/icgc-argo/workflow-ui/pull/76

Manually triggered redeploys have been required to restore environment variables following these PRs.

**Comment by akachru-github** [comment]
issue was addressed by @lepsalex last week. 
closing. 

cc. @mistryrn , @yalturmes
