### ISSUE TITLE
🐛 Policy fix 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-ui#95]
QA has 2 policies
-` rdpc-collab` and `RDPC-CA`
-` rdpc-collab` is deciding if people have read/write access on UI
- `RDPC-CA` is read/write to services (what the api is actually using)

We do not need 2 different policies here for this, or should we only be using RDPC-CA

- [x] make an RDPC-infra update to change the rdpc_region env var from `collab` to `CA`
- [ ] for deploy, verify in dev/qa/prod

**Comment by andricDu** [comment]
I can confirm, prod is only using RDPC-CA
